server:
  port: ${SERVER_PORT}

spring:
  application:
    name: reservation-service
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  profiles:
    active: local

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
