server:
  port: 8083

spring:
  application:
    name: reservation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: root
  zipkin:
    base-url: http://localhost:9411/
  jpa:
    hibernate:
      ddl-auto: create-drop

springdoc:
  api-docs:
    path: /api-docs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
