-- Table: public.hotel

-- DROP TABLE public.hotel;

CREATE TABLE public.hotel
(
    id            integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    hotel_address character varying(255),
    hotel_name    character varying(255),
    hotel_phone   character varying(255),
    CONSTRAINT hotel_pkey PRIMARY KEY (id)
);

-- Table: public.room

-- DROP TABLE public.room;

CREATE TABLE public.room
(
    id              integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    capacity        integer NOT NULL,
    price_per_night numeric(19, 2),
    room_status     character varying(255),
    room_type       character varying(255),
    CONSTRAINT room_pkey PRIMARY KEY (id),
    hotel_id        integer NOT NULL REFERENCES public.hotel (id)
)

